name: Trendify Auto-Pilot

on:
 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Libraries
        run: pip install feedparser google-genai requests tweepy

      - name: Run Trendify Bot
        env:
          GEMINI_KEY_1: ${{ secrets.GEMINI_KEY_1 }}
          GEMINI_KEY_2: ${{ secrets.GEMINI_KEY_2 }}
          GEMINI_KEY_3: ${{ secrets.GEMINI_KEY_3 }}
          GEMINI_KEY_4: ${{ secrets.GEMINI_KEY_4 }}
          GEMINI_KEY_5: ${{ secrets.GEMINI_KEY_5 }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: python main.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "Trendify-Bot"
          git config --global user.email "bot@trendify.com"
          git add .
          git commit -m "Auto-published new article 🚀" || echo "No changes"
          git push
